# Generated by Django 2.1.3 on 2019-03-08 02:31

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vicinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(2, 'Enabled'), (-2, 'Disabled')], default=2, verbose_name='Status')),
                ('projectName', djongo.models.fields.DictField(default={}, verbose_name='projectName')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Create Time')),
            ],
        ),
    ]
